language: node_js
node_js:
  - 6

script: npm run build

deploy:
  provider: s3
  access_key_id: "AKIAIUJH7YPKVR4UHFUQ"
  bucket: "lu-tech"
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  on:
    branch: b-travis-integration