language: node_js
node_js:
- 6
script: npm run build
deploy:
  provider: s3
  access_key_id: AKIAIHIWV5PJM3GGNEEA
  secret_access_key:
    secure: G4kBHwrvuY4rq2lS8ivNLPicj66bOHNVcYXPWLORkwYXRdLxzem2UHePkfZNnZ4alPk3kHhzps5J6Nv1cIMu45t9ir4yiGIXP1JIEw9lk+upn0IYksO3eR/m8ydOraIO0QE2JctRzrFM875eCe7ODOzPb3xOjjOj2DWTuZDuekfgvIj3HycpYm/B31GViYhb0FmtJlk3cNaZgucLOE6ki5A/HGEPhB8gxK21ltcWcynPjxzmbbD618KRjzX3El2Yom5grGpibvAaqQ6gbNR38NCquV7iz6Njbofad73QeMqHYX1YjhG0MWo5486z80n3q+jwzP7dUxz/vlLVAQbhn5y3OVzl5vbZ2uA2R9CgPpJtZr92E3hjMClz1htkLuDlJH2GL173MOSirSlAYb0n+VJ13GgIWtSgOT96natMzjh3vSx4JJRxKxQBHBxydzoOiopXeNWfRu2cScAzKFu7FrI8FyxPeOWvc/yBrWX5ESRVdvSyKhtqkqni+jJcMtiiQPD9+Wat5uZIW3k4Odmfnbpg6AnBOL+4mYzHd3NWCOtacwfjRCCjG9Rqy2a5YWBKDrsmGvF6G4oJmfZDWzhbTSgCH1GT82n3zd+Zic++4nZWlYRQVCbAVwCB0CzAShYBJcRio54Hj69ifG/ny92GjdPAUqcak/5sz5I8px0pOmo=
  bucket: lu-tech
  region: eu-central-1
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  on:
    branch: b-travis-integration